---
dependencies:
  service/[^/]*:
    tokens:
      logging:
        service: logging
        secret: loggingSecret
  service/social:
    preshare:
      - clientSecret
  service/logging:
    preshare:
      - clientSecret
    secrets:
    - loggingSecret
  service/banking:
    preshare:
      - clientSecret
      - realmSecret
  service/authentication:
    preshare:
    - clientSecret
  service/realmregistry:
    preshare:
    - clientSecret
    secrets:
    - realmSecret
  realm/[^/]*:
    preshare:
    - global
    secrets:
    - secret
    tokens:
      logging:
        service: logging
        secret: loggingSecret
      authentication:
        service: realmregistry
        secret: realmSecret
keystores:
  - path: 'conf/system/certificates/keystore.jks'
    password: 'secret'
argon:
  iterations: 1
  memory: 8192
  parallelism: 4
  hashLength: 32
  saltLength: 16
hmacAlgorithm: HmacSHA512
secretBytes: 64
tokenttl: 604800