---
dependencies:
  service/[^/]*:
    preshare:
    - global
    secrets: []
    tokens:
      logging:
        service: logserver
        secret: secret
  service/socialserver:
    preshare:
      - clientSecret
  service/logserver:
    preshare: []
    secrets:
    - secret
    tokens: {}
  service/authserver:
    preshare:
    - clientSecret
    secrets: []
    tokens: {}
  service/realmregistry:
    preshare:
    - clientSecret
    secrets:
    - realmSecret
  realm/[^/]*:
    preshare:
    - global
    secrets:
    - secret
    tokens:
      logging:
        service: logserver
        secret: secret
      authentication:
        service: realmregistry
        secret: realmSecret
keystores:
  - path: 'C:\Users\chili\Documents\chili-game-2ext\prototype\conf\system\certificates\keystore.jks'
    password: 'secret'
argon:
  iterations: 1
  memory: 8192
  parallelism: 4
  hashLength: 32
  saltLength: 16
hmacAlgorithm: HmacSHA512
secretBytes: 64
tokenttl: 604800