---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "gSfQhENKH6lYkAYAccJq9f9reW10qEVylPz1Dou/wSg/9aQRGXiCh+bXJNtEXhhxc1333PIc6oAIM0J/8yhYdw=="
console: false
global: "O1G9N7UV/sm4hB71OtYNSxFYYaMvFo2DDRLJldTWytqdaNysXdVflU7LVAf3IsASFzF59vBuxk4p2v3ELa2pUw=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "z4D8QyI/RIsSsMWvzOYsWrqECTPkIp7bNQAENuZq6N442LdAsnIBSUZd8OY2lKHKIyYTP0MTf0UN/7CedI5KtA=="
  expiry: 1601741780
