---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "G/z4Rsdtw8K1XxVG/FkR+jA+P+qo/PHRDd8LPD+hgNseBJJKAbwgwH11x/nb9q2J8UBOBFjL7nmJwl/fWAqnOQ=="
console: false
global: "Sx3/RiGBuX8yJ585q+zOIuJq35LmEydixHf4FsNu6ltCTmMjIE8SBT0CtoPjTf16eNaGbq8mF6i42u4k/6TbBA=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "7Kpp0G+vi3UeEXRnqFvcRv9OGIA8DQsiVzTT73+S3HdPz522NJdDXUYXWysJ1o1CojMcRunwlSvLXEfBcbUaIg=="
  expiry: 1606513658
