---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "mutable.bunnies.v1"
  port: 9200
  template:
    mappings:
      with_time:
        properties:
          time:
            type: "date"
  enabled: false
console: true
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "A+BVE3GkpZ3DoOYQ4PH/hSEtmDusdbXKqEvVUNo1A8URmhYT0gNReMhWDeOTmfQRCFlY+ptewWJPjFHgPw1Eqw=="
  expiry: 1611934374
clientSecret: "x/CfsbeyIzpRxjkIuxMhrMZa28UaS+fLVxPID1iI3EEjOW1/i5iV0Dz+lGnrbB63+rtn7j/HtHnwSfqZJt+U4Q=="
loggingSecret: "TA+Y0+XhLR79bmfntj8zqiMw0lV1x0JlOn0zap5Oaj3YTKc85odEIGtv9jS4N1ZFTNR+f73AxQQ1wm0yfJ8YlA=="
