---
node: "logging.node"
plugin: "com.codingchili.core.storage.ElasticMap"
console: true
elastic:
  settings:
    index.mapping.total_fields.limit: 3000
  mappings:
    properties:
      timestamp:
        type: "date"
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "UOwuIjK0WG3EX4ifp3jlH5hqMianBL+Brh54Fsw9SShi1rKRzmDGcjz/2ZNdlqUVavM7DVgBXMNQRJcGTWNULQ=="
  expiry: 1612624778
clientSecret: "qkqizlAaO16O919qOPRH0ogu5X7kjX/w4MfMc1NEYc9zwhQYDkNn/VRUhbBYDH4y0zSNniO+OxSgPJaBlEIFqA=="
loggingSecret: "fnDyZIeeIMrthFSvaZpQm6nShVm3W1rHYooYSpIQ9GJRY5HzDDquG05Y8omMZGEH/KYnAeEC91zrlnHhCbYwlg=="
