---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "0VIEzNpd1v46bf7xQENGZMmS1x1ZpXsD4d3khpg+wIL41b/RV/ZPmKKs/B2XgqxYAJzR/KJ2PtnvgPZZNMR7/w=="
console: false
global: "9RuRQkCDidsAWEOAYCa999MkRDmRkHdGWyVnUbhzmbZM7xp88ez45+p+V4NuqzgQs+XctXCD+tQ6Uh1QRUfEFA=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "sg73Qe++AgxnNpUh4OFDXsLzr1TQhkrTn9cBTGqj8DgXTpd6vRHbdi7pvA1eBcodXmKKdyzEHPMum+CvYiGiMA=="
  expiry: 1607477113
