---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "znXe6GT28oVIcoJCo22msz2sy1lheLr76P4iNYrWF8mvXEL0IZAgZ7P/jVn8gUn/EZ5tn08I19Y/qwPd12zW4g=="
console: false
global: "nZwEW+JHJMecgRKwxgCGsNVKSvWSZkUGWlUgYDvyxc1Lm75dzk2PC8ofIgdxyg4ntB801KswA/0vEErhZJsGLQ=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "xz2qbFsmc79vH4j3MiEPLM94B8aLMJAvC4Vzaw4eNI38Lz0t3QK0XDT1uZu+JWTF8MZiZeN+WDSTZaew9Tz+MA=="
  expiry: 1607448297
