---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "SpJDdb2G45xxYtWAM6VFrgd5LNvrVWKuciRPwmm0f5Kw2JbtPxEIdQj4VfJk+/bHdiTdii2I+vZaWX0LF0g8Uw=="
console: false
global: "LSc7+5GuvEPkt80gTa9X6IdteHJ++aZWkBYsbWnvB1NpOEP6RcfW03qXNFj9HO4YAUX6JxohipZm51rReU553Q=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "9xh8v/Uh/T04fqMeYLlpU6+1ljFlzKYjQ6likipTBsLnb9mJUDwwWt6tHNFLeSmoCkkWFycJdDpe8aBWTITd5w=="
  expiry: 1599990680
