---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "oGkKTJgvrTwqp3LryWm+akVZiJLChqv9Mnmw+cL4CADlRxHrYIK68aC2oux6xcCol1zTb5v8ZyzpTaGRzlWWCw=="
console: false
global: "haZfBOWodqTjJTiU66KR+6nXfkSdM0G/PBQHikkaKrZX1hAjzKi1eM9odirTf9s8duUNQsPcdknDUoiNxFOBkg=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "ThTdI9T0Leu+9x0TfEW8LKgrYUoW4TaLYQUW9RS+slJOipdS0sWt0nNnQFwIMOlFGm+b59FCHBR9X1M9KOwjtA=="
  expiry: 1607675811
