---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "X0BOgIVXERcvR0B+JMnMOTntW6/uREe9T5Sd7tbZcsVVt4QdsH2LlbMGOP3//xrYewKCVONZK3pRGVyCDxdLBA=="
console: false
global: "WbO+PU0XdlSW+1u+3w2Thwrk/GgERbr8QC5TNP3HS6Su46BmPL1utM4lYtTtsZRRIs9Urau21TdY8FOvNOAIsQ=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "Eif3Qo7HnneWcJxY6xkyofORSsREYc6BheZOakcKfGyMcW/45f9pMopRUUw3IxC47qCJIjFnEuJQcevoxnS/Pw=="
  expiry: 1610659335
