---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "2txJz1TI9EXwdspxwIA7ku/8c+E2HWQFkOyqYq92OWn9Mu1WhwAZ1NJPg5F+zC7GLrfEDmbYiQE0M59/Hp9Oug=="
console: false
global: "mUKc8RPkR0LBnUin/9/T4/QrWlOQ/N0G+YoGMftCUPmzRmqU13bZxuNbeEAY7YSsbDH2O50yLtvkzG7GeOf6sg=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "ZXFhIVfa2vYbOasaagl/QwpcN+TaHGhfGcNWGpKycwgPg3Rs/zL8oGvb4EMqON76OxFGkdeOEJiAfGn18Hjxvg=="
  expiry: 1607395005
