---
node: "logging.node"
plugin: "com.codingchili.core.storage.ElasticMap"
console: true
storage: false
elastic:
  settings:
    index.mapping.total_fields.limit: 3000
  mappings:
    properties:
      timestamp:
        type: "date"
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "5T6EB+6NPP5MUvzmUP5dFlhq1PcGROwPjKN5Jyq9rlTwcmbEmjWswwkOqpBvrYr01tJUqaE3prqXxqG6k75/Lw=="
  expiry: 1616167944
clientSecret: "44f7w8ASSgsNnoJxtk2furtHy+H7qWJcDOTnvsTxcCmS2dhp+ozNDWVMvwdOgJnAXfbi0jecucZsGY+qJrensA=="
loggingSecret: "pJmtDrRqG2GjCRt9urrUnqTNITdjxMgDdQkMt/0k3wa8SRrDgw0V5kbvskH1b3KCcXG+2MyXZBrFUh8LKyMH7Q=="
