---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "iXfyeZPSOMItXkytGcTWX9vuvBL2PTIUx8V+1YL3FcGwcFqidnV7k7QF5S+n2OzT/0gg5Bbk3SyI3c466zbhbw=="
console: false
global: "InRD0Qo6P4vXuf8i9Mt7l/usVWpVmIbgfYQdUKpssJhkRSSoZsQhHn9BeOaIeTFfLuGcakeQmwENyYduAEuFLQ=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "Ycm4XU1f7AvXejX+X///yf/trVPESHONGf72zrFcmFwzy9WqgK+s/k043AgQO9IgpGdhDy9F0oAZW10X7zqbOg=="
  expiry: 1600708625
