---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "c6wQ3txSHqIH9xYW9SnVQ0xaDLTYfSQinH0QMVHuGZvO134PbwjXArswcE2vppmYFbqHDvVBx7R9TmQXL7WY6Q=="
console: false
global: "UHF5m7xj1GEw4uVubgY+mpdmjn5Dfuw3w1BmkUnCYQAP7cfHn+8ZFx0yOZXtfPjk7EXUePiYakXTGY9TzvrCtg=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "rFAmKXsl7t9MZV4XIC2u7GoqSkDPvggEgOOEHsCcYYMBv7zmUBV5JwzcrvC4Nr01UENvmuTOsOiaHUnqk+0BKQ=="
  expiry: 1611312925
