---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "6BvRYU8z2VTMuE2kOm5JQHoIszh3Y9PoFy4YUWUMBLO3q7J+hV5UJaogBCuKMYumU6muLI+ektQ/7Q/5xLcPdg=="
console: false
global: "YF2cnn9NKZY2d1aqBWc1grOi9iy75oB3O703Cao5FGxCKGpLVm6/WM95rVvINNYlJiDJaFslKqMQYPnP7wF1cQ=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "rFWum8/XURrLe1d+TqWo1rODQ5L9fDlB0wI7kadzkgiZeNr8WGjjLAW2UdTfnwxMVxRxT2WLgINwHSUPBf0xSg=="
  expiry: 1606466153
