---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "XwKXBS2Qg6qHQg+WAN1wF03d46VkFOwvfQtSIJy6VvsDcxK1a/OQ28l+eTLkc/f5ybad0qvpNbb/qcxAnaF20Q=="
console: false
global: "sOboFELtoEvCwBJmSnatgOYwcTPjm0m/fcjJXkqPDNR7B+JUJhYD8xH+xza6BffiJabZP6gXkf+b0NfV5I0f9w=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "gjk047d8b0eI3cA8wa2XzXugUOuvSh1Hrrafbrn7P8+f62in/CQADy2h/KSeyhPujMHuqwEDMv9HOS0UT/pAKA=="
  expiry: 1607694280
