---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "AGzlb99xmzlwEQW0KJDyzCaH6jzgxqb92792RQDy/1NyiiNnin+yCIzlKHLPLyuBGWVDLzvcuN1cvwccVOaOKQ=="
console: false
global: "Q3qce4m4+l8gb1jtm8L2ZUQCHzBWqoYq8Hu5KcVLY2h/Djj3PCCRV7FQ8/erfBCOtTdfk8XLeM6Gd/UXs7EY2w=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "SnYqnFL211FnrkUDgP80dXUPVbkQ0uSRWfieL49mnBIEM47EhJkTINl92dTHXLwU7PS8OkVCEL6cln4Cfs39AQ=="
  expiry: 1600012962
