---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "f2caKpQ5pi9GlAGtqPFXzHKzUfm9Aa1WkYb2zQCg50xpkw/OaYm5ABb/7rxien9lL0dT6n2EOwKS6ioJNSh+vg=="
console: false
global: "nDhIAhndMOADTjAsR8z8+3vqVSWWcui4kYipDCHY/pZSvFKcnRk57teX4R3EFdoy3bX8TgTsveAkOa1UUuvYng=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "c1A6cDfhASWggR6qVbO7UO3StA4sSD9qY283RauLjriaH+kX4lX9GTpZBArZarDNqk4S6xxL8I/vzmrKfGgFbg=="
  expiry: 1606844919
