---
node: "logging.node"
plugin: "com.codingchili.core.storage.ElasticMap"
console: true
elastic:
  settings:
    index.mapping.total_fields.limit: 3000
  mappings:
    properties:
      timestamp:
        type: "date"
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "sjOcVsoCPs2G7E7jYi/je4XKYAYs76nZdY14DkOkJ38aPNCSZPhu6vLyTEkzaU6ny0/ayxE0kKsoe938q+9CyA=="
  expiry: 1615301668
clientSecret: "5z83Of+giyv++8JXS/CInH7VDKn+KoQb4OcqUE8dzgAzt2tJdjKKEGsNyq3Lmv/+4u9Z125PRaNZMsq3u2iA8g=="
loggingSecret: "r73COO8mEwBQLoMbmcwLbgqXSdqzRAgLOjaODELkysNyvrhpfTOFnvy5Uhh/VCrD3b6AroJTC0aaANpQLa2ghw=="
