---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "qzEyo9C9g9Kmap0+qaKp7cirJ4ZVJQzulYW7tP4QN+EFt7yDjJik3H2CQvAA5MzkqKjtJv85rc92xgI/6F8eYw=="
console: false
global: "IK6dMWQAn648CJRBzm+prZUnaC0CiissaLGtL5zhleiIKUkHhkkpjj2qEvFdeiJU79T+Xfgt/iUakgY05Zxg1A=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "tggrtb+xLseqlq2yUW2y06L8gV3kaFQcXRtqiM656+b8OTNOVKAC6jX3e3Uzx6UUZurgc5GUtEg4KBBKWOj5Tw=="
  expiry: 1606219729
