---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "L7QHVeFQbedOu0k/0v/6wFfB6YhEaKsAWmcYNt3xlLeCHQRy/ImHeQzBMCc80TRYCgsDOlfO/2aShbnE3KhtNw=="
console: false
global: "SCZxrZ11Bj1TIwv/eIAYvjxGbODJdG/zerOQMgNTb5fvujYWQBAaUy+lxv+pdG/K/vlcPxnUHaDJI7xAD1Zwrg=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "axzbmWEHAbb3qWZs29c1/wEP4RUtAzdi9YAutg1zFuMHfdoxxM0FBUUCn0ez6BbPbYREbIxDwjVIF+P72F2Ybg=="
  expiry: 1607631974
