---
node: "logging.node"
elastic:
  remote: "localhost"
  index: "chili.core.logging.v101"
  port: 9200
  template:
    mappings:
      the_def_index:
        properties:
          time:
            type: "date"
  enabled: false
secret: "HlXJEFaQ5MaT2xAOR7GOs4goy5OdUGPYIAGUyERafnQ7XSE6l3Ra9f9mNTTp6EU+oP/LnqG0XQZHHrive72w7g=="
console: false
global: "IXx9HsEdEoHa70EBnW24rA/Qj9jXRNhdY4K7TVWw6iKTxqhqDpXs9kzhbG9Y+DsF3voi8uc8fq+XqbZ+qiWnlQ=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "logging.node"
  key: "E/pvKDO+4BzGGIDNjnhWxUZSTohUZVml6T1cto/EuBOuBI8QfCRlIcQSOid90clbwcCoBKwH5qn1GyofAnTsZw=="
  expiry: 1605281602
