---
node: "routing.node"
transport:
- api:
    /api/realmlist:
      target: "client.realmregistry.node"
      route: "realmlist"
  type: "REST"
  secure: false
  port: 1443
  timeout: 3000
  maxRequestBytes: 512
  defaultTarget: "webserver.node"
external:
  client.authentication.node: ".*"
  client.realmregistry.node: ".*"
  auction.node: ".*"
  social.node: ".*"
global: "LSc7+5GuvEPkt80gTa9X6IdteHJ++aZWkBYsbWnvB1NpOEP6RcfW03qXNFj9HO4YAUX6JxohipZm51rReU553Q=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "routing.node"
  key: "SniT/G1oMzq6MrnrAxzzyq3uihI9WdXKoBipL0834GYANlSLs8/ScOx3sbucToW8l4Krhjk0Z5yKdGMxttOm5w=="
  expiry: 1599990680
