---
node: "routing.node"
transport:
- api:
    /api/realmlist:
      target: "client.realmregistry.node"
      route: "realmlist"
  type: "REST"
  secure: false
  port: 1443
  timeout: 3000
  maxRequestBytes: 512
  defaultTarget: "webserver.node"
external:
  client.authentication.node: ".*"
  client.realmregistry.node: ".*"
  auction.node: ".*"
  social.node: ".*"
global: "sOboFELtoEvCwBJmSnatgOYwcTPjm0m/fcjJXkqPDNR7B+JUJhYD8xH+xza6BffiJabZP6gXkf+b0NfV5I0f9w=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "routing.node"
  key: "KQJIBmRtHU97vVoGTXPuFsag5k41Mw8+FTpBnQ2Z1x34FqLMIE59sCJhLyyrWsJRNvlJbESOiqBfG/ndxmsOvQ=="
  expiry: 1607694280
