---
node: "routing.node"
transport:
- api:
    /api/realmlist:
      target: "client.realmregistry.node"
      route: "realmlist"
  type: "REST"
  secure: false
  port: 1443
  timeout: 3000
  maxRequestBytes: 512
  defaultTarget: "webserver.node"
external:
  client.authentication.node: ".*"
  client.realmregistry.node: ".*"
  auction.node: ".*"
  social.node: ".*"
global: "O1G9N7UV/sm4hB71OtYNSxFYYaMvFo2DDRLJldTWytqdaNysXdVflU7LVAf3IsASFzF59vBuxk4p2v3ELa2pUw=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "routing.node"
  key: "8W8P9lgsMoMMz+T5bIZ0o9mfpy2XeArtrs2WLVg+YyxI15sTx/2i/HA6r9ZaCboiQJzJNCnDwu6XH81K5Xcuxg=="
  expiry: 1601741780
