---
node: "routing.node"
transport:
- api:
    /api/realmlist:
      target: "client.realmregistry.node"
      route: "realmlist"
  type: "REST"
  secure: false
  port: 1443
  timeout: 3000
  maxRequestBytes: 512
  defaultTarget: "webserver.node"
external:
  client.authentication.node: ".*"
  client.realmregistry.node: ".*"
  auction.node: ".*"
  social.node: ".*"
global: "IK6dMWQAn648CJRBzm+prZUnaC0CiissaLGtL5zhleiIKUkHhkkpjj2qEvFdeiJU79T+Xfgt/iUakgY05Zxg1A=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "routing.node"
  key: "vS5fw+V24nDnYDb3JRSKSCrtOpHEP+Dp6ID/GfhKk51MSD3r7YwIVNeJiIAIE2tru/avIu8iscC4wxp3yIg+aQ=="
  expiry: 1606219729
