---
node: "routing.node"
transport:
- api:
    /api/realmlist:
      target: "client.realmregistry.node"
      route: "realmlist"
  type: "REST"
  secure: false
  port: 1443
  timeout: 3000
  maxRequestBytes: 512
  defaultTarget: "webserver.node"
external:
  client.authentication.node: ".*"
  client.realmregistry.node: ".*"
  auction.node: ".*"
  social.node: ".*"
  banking.node: ".*"
global: "WbO+PU0XdlSW+1u+3w2Thwrk/GgERbr8QC5TNP3HS6Su46BmPL1utM4lYtTtsZRRIs9Urau21TdY8FOvNOAIsQ=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "routing.node"
  key: "8UZyPJ8pxQClOhVGdK+q1KGvpUhSsdLVWCBbYztLNIkCjo5/cuWPcFGACEFUzpcuDcG4N6NBaXaHCPQP+4vhqg=="
  expiry: 1610659335
