---
node: "routing.node"
transport:
- api:
    /api/realmlist:
      target: "client.realmregistry.node"
      route: "realmlist"
  type: "REST"
  secure: false
  alpn: true
  port: 1443
  timeout: 3000
  maxRequestBytes: 1024
  defaultTarget: "webserver.node"
external:
  client.authentication.node: ".*"
  client.realmregistry.node: ".*"
  client.logging.node: ".*"
  auction.node: ".*"
  social.node: ".*"
  banking.node: ".*"
global: "OzDQE8uwrs3AsWPQxyR+RollbEq5ETQkuwMz/S08wKvst8+ERIMr+X6wTzyrPjZ1GNTH2SHYy8BJetFRTxnH9Q=="
logging:
  properties:
    type: "HmacSHA512"
  domain: "routing.node"
  key: "+nPndoWJ54HAy3/86Obu/BBCMBm+0fcp1XfWEI52n4gF0J3Yybkwn63DpwrlNhIBz+QlqycnZPxUOVh1cdQHFg=="
  expiry: 1615301669
